### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by smilehari** [ketanpatel25/GCM-Demo#1]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ketan.demo/com.ketan.demo.DemoActivity}: java.lang.UnsupportedOperationException: Device does not have package com.google.android.gsf

**Comment by ketanpatel25** [comment]
hii.....where is bug. can you explain more

**Comment by smilehari** [comment]
07-02 18:21:58.703: E/AndroidRuntime(1186): FATAL EXCEPTION: main
07-02 18:21:58.703: E/AndroidRuntime(1186): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ketan.demo/com.ketan.demo.DemoActivity}: java.lang.UnsupportedOperationException: Device does not have package com.google.android.gsf
07-02 18:21:58.703: E/AndroidRuntime(1186):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1647)
07-02 18:21:58.703: E/AndroidRuntime(1186):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
07-02 18:21:58.703: E/AndroidRuntime(1186):     at android.app.ActivityThread.access$1500(ActivityThread.java:117)
07-02 18:21:58.703: E/AndroidRuntime(1186):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
07-02 18:21:58.703: E/AndroidRuntime(1186):     at android.os.Handler.dispatchMessage(Handler.java:99)
07-02 18:21:58.703: E/AndroidRuntime(1186):     at android.os.Looper.loop(Looper.java:123)
07-02 18:21:58.703: E/AndroidRuntime(1186):     at android.app.ActivityThread.main(ActivityThread.java:3683)
07-02 18:21:58.703: E/AndroidRuntime(1186):     at java.lang.reflect.Method.invokeNative(Native Method)
07-02 18:21:58.703: E/AndroidRuntime(1186):     at java.lang.reflect.Method.invoke(Method.java:507)
07-02 18:21:58.703: E/AndroidRuntime(1186):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
07-02 18:21:58.703: E/AndroidRuntime(1186):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
07-02 18:21:58.703: E/AndroidRuntime(1186):     at dalvik.system.NativeStart.main(Native Method)
07-02 18:21:58.703: E/AndroidRuntime(1186): Caused by: java.lang.UnsupportedOperationException: Device does not have package com.google.android.gsf
07-02 18:21:58.703: E/AndroidRuntime(1186):     at com.google.android.gcm.GCMRegistrar.checkDevice(GCMRegistrar.java:83)
07-02 18:21:58.703: E/AndroidRuntime(1186):     at com.ketan.demo.DemoActivity.onCreate(DemoActivity.java:51)
07-02 18:21:58.703: E/AndroidRuntime(1186):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
07-02 18:21:58.703: E/AndroidRuntime(1186):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
07-02 18:21:58.703: E/AndroidRuntime(1186):     ... 11 more

**Comment by smilehari** [comment]
GCMRegistrar.checkDevice(this); creates the problem

**Comment by ketanpatel25** [comment]
ok you can try    GCM-Demo / gcm / samples / gcm-demo-client  project this one is run or some problem

**Comment by ketanpatel25** [comment]
gcm.jar file add or not add

**Comment by smilehari** [comment]
the jar file is available in the lib

**Comment by ketanpatel25** [comment]
hii...
you can try this one project
this project working.
i will test in nexus one Devies or HTC,nexus S
working

me be you server sied code som errar

**Comment by ketanpatel25** [comment]
you see log in 'regId' get or not ?

**Comment by smilehari** [comment]
Hi Im texting in the emulator.. Im updating all the sdk available and then will retry yesterday i jus downloaded the GCM sdk.. 
The problem is with GCMRegistrar.checkDevice(this); if i comment this line the app works..
Can you guide me to some proper tutorial to develop the server side coding for push notifications.. I ve never done server side coding before.. If you can give me some good reference i will ask ma colleagues(.net developers) to develop the server side code for me..

**Comment by ketanpatel25** [comment]
ok...
this project working in device not work in emulator 
emulator not supporting, emulator RegID not generate

**Comment by ketanpatel25** [comment]
ok...
this project working in device not work in emulator 
emulator not supporting, emulator not generate RegID

**Comment by ketanpatel25** [comment]
ok...
this project working in device not work in emulator 
emulator not supporting, emulator not generate RegID

**Comment by smilehari** [comment]
okie thanks a lot for ur help ketan will check in device later 

Can you guide me to some proper tutorial to develop the server side coding for push notifications.. I ve never done server side coding before.. If you can give me some good reference or sample code i will ask ma colleagues(.net developers) to develop the server side code..

**Comment by smilehari** [comment]
okie thanks a lot for ur help ketan will check in device later 

Can you guide me to some proper tutorial to develop the server side coding for push notifications.. I ve never done server side coding before.. If you can give me some good reference or sample code i will ask ma colleagues(.net developers) to develop the server side code..

**Comment by ketanpatel25** [comment]
thanks....

as regarding you server side problem. i think below link in project code there you try it
GCM-Demo / gcm / samples / gcm-demo-server
